import mongoose from "mongoose";

/**
 * SKU schema definition for Mongoose.
 */
const skuSchema = new mongoose.Schema(
    {
        // Unique identifier for each SKU, automatically generated by MongoDB
        id: {
            type: String,
            default: () => new mongoose.Types.ObjectId().toString(),
        },

        // SKU number for the product
        sno: {
            type: Number,
            required: true,
        },

        // Name of the product
        productName: {
            type: String,
            required: true,
        },

        // URL of the input image associated with the SKU
        inputImageUrl: {
            type: Array,
            required: true,
        },

        // Link to the Order model to associate SKUs with an order
        order: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Order',
            required: true,
        }
    },
    {
        // Automatically include `createdAt` and `updatedAt` timestamps
        timestamps: true,
    }
);

// Export the model
export const Sku = mongoose.model("Sku", skuSchema);
